/**
 * @constant BASE_URL
 * @type {string}
 */
export const BASE_URL = 'https://emojipedia.org';
export const APP_START = 'APP_START';
export const APP_DONE = 'APP_DONE';
export const APP_READY = 'APP_READY';
export const ERROR = 'ERROR';

export const FETCHER_FETCH_CATEGORIES_ERROR = 'FETCHER_FETCH_CATEGORIES_ERROR';
export const FETCHER_FETCH_CATEGORIES_SUCCESS = 'FETCHER_FETCH_CATEGORIES_SUCCESS';
export const FETCHER_FETCH_CATEGORY_ERROR = 'FETCHER_FETCH_CATEGORY_ERROR';
export const FETCHER_FETCH_CATEGORY_SUCCESS = 'FETCHER_FETCH_CATEGORY_SUCCESS';
export const FETCHER_FETCH_EMOJI_ERROR = 'FETCHER_FETCH_EMOJI_ERROR';
export const FETCHER_FETCH_EMOJI_SUCCESS = 'FETCHER_FETCH_EMOJI_SUCCESS';
export const FETCHER_FETCH_IMAGE_ERROR = 'FETCHER_FETCH_IMAGE_ERROR';
export const FETCHER_FETCH_IMAGE_SUCCESS = 'FETCHER_FETCH_IMAGE_SUCCESS';

export const PARSER_PARSE_CATEGORIES_SUCCESS = 'PARSER_PARSE_CATEGORIES_SUCCESS';
export const PARSER_PARSE_CATEGORY_SUCCESS = 'PARSER_PARSE_CATEGORY_SUCCESS';
export const PARSER_FOUND_MODIFIERS = 'PARSER_FOUND_MODIFIERS';
export const PARSER_FOUND_THEME = 'PARSER_FOUND_THEME';

export const EXTENTIONS = {
  sass: 'scss',
  less: 'less',
};
